from __future__ import annotations

from io import BytesIO

from reportlab.lib import colors

from agents.crew import AnalysisResult, CaseInput


def build_report_pdf(case_id: int, case: CaseInput, result: AnalysisResult) -> bytes:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=42, leftMargin=42, topMargin=42, bottomMargin=42)
    styles = getSampleStyleSheet()
    title_style = styles["Title"]
    heading_style = styles["Heading2"]
    normal_style = styles["BodyText"]
    normal_style.leading = 14

    story = [
        Paragraph(f"MedOrchestra Case Report #{case_id}", title_style),
        Spacer(1, 10),
        Paragraph(
            "Educational decision-support report only. Not a diagnosis or substitute for licensed medical care.",
            normal_style,
        ),
        Spacer(1, 14),
        Paragraph("Patient Intake", heading_style),
        Paragraph(_escape(case.to_prompt()).replace("\n", "<br/>"), normal_style),
        Spacer(1, 12),
        Paragraph("Final Report", heading_style),
        Paragraph(_markdown_to_reportlab(result.final_report), normal_style),
    ]

    if result.research_summary:
        story.extend(
            [
                Spacer(1, 12),
                Paragraph("Research Summary", heading_style),
                Paragraph(_markdown_to_reportlab(result.research_summary), normal_style),
            ]
        )

    if result.specialist_opinions:
        story.append(Spacer(1, 12))
        story.append(Paragraph("Specialist Opinions", heading_style))
        for name, content in result.specialist_opinions.items():
            story.append(Paragraph(_escape(name), styles["Heading3"]))
            story.append(Paragraph(_markdown_to_reportlab(content), normal_style))
            story.append(Spacer(1, 8))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buffer.getvalue()


def _footer(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(42, 24, "Generated by MedOrchestra. Confirm all findings with a licensed clinician.")
    canvas.restoreState()


def _markdown_to_reportlab(text: str) -> str:
    escaped = _escape(text)
    lines = []
    for line in escaped.splitlines():
        stripped = line.strip()
        if stripped.startswith("## "):
            lines.append(f"<b>{stripped[3:]}</b>")
        elif stripped.startswith("# "):
            lines.append(f"<b>{stripped[2:]}</b>")
        elif stripped.startswith("- "):
            lines.append(f"&bull; {stripped[2:]}")
        else:
            lines.append(stripped)
    return "<br/>".join(lines)


def _escape(text: str) -> str:
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
